spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
security:
  jwt:
    secret-key: 1e7088a9cac589687f8421ba722b91e20e4c8afda135fc4bb1edb870beb2f18c
    expiration-time: 600000
  internal-secret: abcdefg