services:

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVER=discovery-server

  discovery-server:
    build:
      context: ./naming-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker  
      

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8004:8004"
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  users-service:
    build:
      context: ./users-service
    ports:
      - "8001:8001"
    depends_on:
      - discovery-server
      - config-server
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  polls-service:
    build:
      context: ./polls-service
    ports:
      - "8002:8002"
    depends_on:
      - discovery-server
      - config-server
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  submissions-service:
    build:
      context: ./submissions-service
    ports:
      - "8003:8003"
    depends_on:
      - discovery-server
      - config-server
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
