spring:
  application:
    name: users-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
logging:
  level:
    org.springframework.security: DEBUG