spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8400/realms/open-polls-realm