spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8400/realms/open-polls-realm