eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  jwt:
    secret-key: 1e7088a9cac589687f8421ba722b91e20e4c8afda135fc4bb1edb870beb2f18c
spring:
  cloud:
    gateway:
      routes:
        - id: users-service-legacy
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/users(?<args>.*),/v1/users${args}

        - id: users-service-v1
          uri: lb://users-service
          predicates:
            - Path=/v1/users/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: submissions-service-legacy-v1
          uri: lb://submissions-service
          predicates:
            - Path=/polls/*/submissions/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/polls/(?<args1>.*)/submissions/(?<args2>.*),/v1/submissions/byPoll/${args1}/${args2}

        - id: polls-service-legacy
          uri: lb://polls-service
          predicates:
            - Path=/polls/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/polls(?<args>.*),/v1/polls${args}

        - id: submissions-service-legacy-public
          uri: lb://submissions-service
          predicates:
            - Path=/public/polls/*/submissions/**
          filters:
            - RewritePath=/public/polls/(?<args>.*)/submissions,/public/v1/submissions/byPoll/${args}

        - id: polls-service-legacy-public
          uri: lb://polls-service
          predicates:
            - Path=/public/polls/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/public/polls(?<args>.*),/public/v1/polls${args}

        - id: polls-service-v1
          uri: lb://polls-service
          predicates:
            - Path=/v1/polls/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: auth-service-legacy
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/auth(?<args>.*),/v1/auth${args}

        - id: auth-service-v1
          uri: lb://auth-service
          predicates:
            - Path=/v1/auth/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: submissions-service-legacy-v2
          uri: lb://submissions-service
          predicates:
            - Path=/submissions/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/submissions(?<args>.*),/v1/submissions${args}

        - id: submissions-service-v1
          uri: lb://submissions-service
          predicates:
            - Path=/v1/submissions/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
server:
  port: 5000
