eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: users-service-v1
          uri: lb://users-service
          predicates:
            - Path=/v1/users/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: polls-service-legacy
          uri: lb://polls-service
          predicates:
            - Path=/polls/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
            - RewritePath=/polls(?<args>.*),/v1/polls${args}
        - id: polls-service-v1
          uri: lb://polls-service
          predicates:
            - Path=/v1/polls/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: auth-service-v1
          uri: lb://auth-service
          predicates:
            - Path=/v1/auth/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: submissions-service-v1
          uri: lb://submissions-service
          predicates:
            - Path=/v1/submissions/**
          filters:
            - RemoveRequestHeader= Cookie,Set-Cookie
server:
  port: 5000
