server:
  port: 8003
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
      hibernate:
        ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.francisco.submissions_service.v1.event,com.francisco.polls_service.v1.event"
        spring.json.type.mapping: com.francisco.polls_service.v1.event.RemovedEntityEvent:com.francisco.submissions_service.v1.event.RemovedEntityEvent
    admin:
      auto-create: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka