/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.francisco.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RemovedEntityEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 506371149733275554L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RemovedEntityEvent\",\"namespace\":\"com.francisco.events\",\"fields\":[{\"name\":\"entityName\",\"type\":\"string\"},{\"name\":\"entityId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RemovedEntityEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RemovedEntityEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RemovedEntityEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RemovedEntityEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RemovedEntityEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RemovedEntityEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RemovedEntityEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RemovedEntityEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RemovedEntityEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence entityName;
  private long entityId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RemovedEntityEvent() {}

  /**
   * All-args constructor.
   * @param entityName The new value for entityName
   * @param entityId The new value for entityId
   */
  public RemovedEntityEvent(java.lang.CharSequence entityName, java.lang.Long entityId) {
    this.entityName = entityName;
    this.entityId = entityId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return entityName;
    case 1: return entityId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: entityName = (java.lang.CharSequence)value$; break;
    case 1: entityId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'entityName' field.
   * @return The value of the 'entityName' field.
   */
  public java.lang.CharSequence getEntityName() {
    return entityName;
  }


  /**
   * Sets the value of the 'entityName' field.
   * @param value the value to set.
   */
  public void setEntityName(java.lang.CharSequence value) {
    this.entityName = value;
  }

  /**
   * Gets the value of the 'entityId' field.
   * @return The value of the 'entityId' field.
   */
  public long getEntityId() {
    return entityId;
  }


  /**
   * Sets the value of the 'entityId' field.
   * @param value the value to set.
   */
  public void setEntityId(long value) {
    this.entityId = value;
  }

  /**
   * Creates a new RemovedEntityEvent RecordBuilder.
   * @return A new RemovedEntityEvent RecordBuilder
   */
  public static com.francisco.events.RemovedEntityEvent.Builder newBuilder() {
    return new com.francisco.events.RemovedEntityEvent.Builder();
  }

  /**
   * Creates a new RemovedEntityEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RemovedEntityEvent RecordBuilder
   */
  public static com.francisco.events.RemovedEntityEvent.Builder newBuilder(com.francisco.events.RemovedEntityEvent.Builder other) {
    if (other == null) {
      return new com.francisco.events.RemovedEntityEvent.Builder();
    } else {
      return new com.francisco.events.RemovedEntityEvent.Builder(other);
    }
  }

  /**
   * Creates a new RemovedEntityEvent RecordBuilder by copying an existing RemovedEntityEvent instance.
   * @param other The existing instance to copy.
   * @return A new RemovedEntityEvent RecordBuilder
   */
  public static com.francisco.events.RemovedEntityEvent.Builder newBuilder(com.francisco.events.RemovedEntityEvent other) {
    if (other == null) {
      return new com.francisco.events.RemovedEntityEvent.Builder();
    } else {
      return new com.francisco.events.RemovedEntityEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RemovedEntityEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RemovedEntityEvent>
    implements org.apache.avro.data.RecordBuilder<RemovedEntityEvent> {

    private java.lang.CharSequence entityName;
    private long entityId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.francisco.events.RemovedEntityEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.entityName)) {
        this.entityName = data().deepCopy(fields()[0].schema(), other.entityName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.entityId)) {
        this.entityId = data().deepCopy(fields()[1].schema(), other.entityId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RemovedEntityEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.francisco.events.RemovedEntityEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.entityName)) {
        this.entityName = data().deepCopy(fields()[0].schema(), other.entityName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.entityId)) {
        this.entityId = data().deepCopy(fields()[1].schema(), other.entityId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'entityName' field.
      * @return The value.
      */
    public java.lang.CharSequence getEntityName() {
      return entityName;
    }


    /**
      * Sets the value of the 'entityName' field.
      * @param value The value of 'entityName'.
      * @return This builder.
      */
    public com.francisco.events.RemovedEntityEvent.Builder setEntityName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.entityName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'entityName' field has been set.
      * @return True if the 'entityName' field has been set, false otherwise.
      */
    public boolean hasEntityName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'entityName' field.
      * @return This builder.
      */
    public com.francisco.events.RemovedEntityEvent.Builder clearEntityName() {
      entityName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'entityId' field.
      * @return The value.
      */
    public long getEntityId() {
      return entityId;
    }


    /**
      * Sets the value of the 'entityId' field.
      * @param value The value of 'entityId'.
      * @return This builder.
      */
    public com.francisco.events.RemovedEntityEvent.Builder setEntityId(long value) {
      validate(fields()[1], value);
      this.entityId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'entityId' field has been set.
      * @return True if the 'entityId' field has been set, false otherwise.
      */
    public boolean hasEntityId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'entityId' field.
      * @return This builder.
      */
    public com.francisco.events.RemovedEntityEvent.Builder clearEntityId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RemovedEntityEvent build() {
      try {
        RemovedEntityEvent record = new RemovedEntityEvent();
        record.entityName = fieldSetFlags()[0] ? this.entityName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.entityId = fieldSetFlags()[1] ? this.entityId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RemovedEntityEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RemovedEntityEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RemovedEntityEvent>
    READER$ = (org.apache.avro.io.DatumReader<RemovedEntityEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.entityName);

    out.writeLong(this.entityId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.entityName = in.readString(this.entityName instanceof Utf8 ? (Utf8)this.entityName : null);

      this.entityId = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.entityName = in.readString(this.entityName instanceof Utf8 ? (Utf8)this.entityName : null);
          break;

        case 1:
          this.entityId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










