spring:
  application:
    name: polls-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true
logging:
  level:
    org.springframework.boot.context.config: TRACE
    org.springframework.core.env: TRACE
security:
  jwt:
    secret-key: 1e7088a9cac589687f8421ba722b91e20e4c8afda135fc4bb1edb870beb2f18c