spring:
  application:
    name: polls-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
logging:
  level:
    org.springframework.boot.context.config: TRACE
    org.springframework.core.env: TRACE