spring:
  application:
    name: config-server
  cloud:
    config: 
      server:
        native:
          search-locations: file:./config/
  profiles:
    active: native
server:
  port: 8888
    

